---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Prepare data
```{r}

library(readr)
kraj_2000 <- read_csv("data/kraj_20001112.csv")
kraj_2000$full_name <- unlist(purrr::map(kraj_2000$name, listr::extract_text_before_titles))
kraj_2000$titles <- unlist(purrr::map(kraj_2000$name, listr::extract_titles))
kraj_2000$highest_titles <- listr::recode_titles(kraj_2000$titles)
kraj_2000 <- listr::add_names_to_df(kraj_2000, "full_name")
kraj_2000 <- listr::parse_gender(kraj_2000, "first_name", "last_name")
kraj_2000$approx_birth_year <- 2000 - kraj_2000$age
kraj_2000$row_id <- 1:nrow(kraj_2000)
kraj_2000 %<>% subset(select = c(row_id, first_name, last_name, titles, highest_titles,
                                 gender, approx_birth_year,
                                 occupation, residence, region,
                                 nominate_party, member_party, party,
                                 abs_votes, pct_votes,
                                 rank, mandate))
save(kraj_2000, file = "kraj_2000.RData")

kraj_2004 <- read_csv("data/kraj_20041105.csv")
kraj_2004$full_name <- unlist(purrr::map(kraj_2004$name, listr::extract_text_before_titles))
kraj_2004$titles <- unlist(purrr::map(kraj_2004$name, listr::extract_titles))
kraj_2004$highest_titles <- listr::recode_titles(kraj_2004$titles)
kraj_2004 <- listr::add_names_to_df(kraj_2004, "full_name")
kraj_2004 <- listr::parse_gender(kraj_2004, "first_name", "last_name")
kraj_2004$approx_birth_year <- 2004 - kraj_2004$age
kraj_2004$row_id <- 1:nrow(kraj_2004)
kraj_2004 %<>% subset(select = c(row_id, first_name, last_name, titles, highest_titles,
                                 gender, approx_birth_year,
                                 occupation, residence, region,
                                 nominate_party, member_party, party,
                                 abs_votes, pct_votes,
                                 rank, mandate))
save(kraj_2004, file = "kraj_2004.RData")
```


# Find similar
```{r}
library(DBI)
library(RSQLite)

load("kraj_2000.RData")
load("kraj_2004.RData")


cand <- RSQLite::dbConnect(RSQLite::SQLite(), "candidates.sqlite")
# dbWriteTable(cand, "kraj_2000", kraj_2000)
# dbWriteTable(cand, "kraj_2004", kraj_2004)

find_similar(cand, "kraj_2000", "kraj_2004", 3150, eq = c("first_name", "last_name", "approx_birth_year", "residence", "region"))


df <- find_all_similar(cand, "kraj_2000", "kraj_2004", eq = c("first_name", "last_name", "approx_birth_year", "residence", "region"))
df$from_party <- kraj_2000$party[df$from]
df$to_party <- kraj_2004$party[df$to]
# df$from_party[is.na(df$from_party)] <- "Nekandidovali"
# df$to_party[is.na(df$to_party)] <- "Nekandidovali"

library(dplyr)
df_sum <- df %>% subset(!is.na(from_party) & !is.na(to_party)) %>% group_by(from_party, to_party) %>% summarise(count = n())
library(alluvial)
alluvial(df_sum[, 1:2],
         freq = df_sum$count)

```

